# NumPy Basics

#NumPy stands for Numerical Python and also known as array oriented computing. NumPy is a library written for scientific computing and data analysis. NumPy consists of a powerful data structure called multidimensional arrays. The most basic object in Numpy is the ndarray, or simply an array which is an n-dimensional, homogeneous array. By homogenous, we mean that all the elements in a NumPy array have to be of the same data type, which is commonly numeric (float or integer)

In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
# creating array using .array() method
#Ex1) 
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [4]:
# to check the type
type(arr)

numpy.ndarray

In [5]:
# to get the dimenssion.
arr.shape

(3,)

In [6]:
# to get the data types of the array elements
arr.dtype

dtype('int32')

In [7]:
#Ex2) 2d array
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
type(b)

numpy.ndarray

In [9]:
b.shape

(3, 3)

In [10]:
b.dtype

dtype('int32')

In [11]:
#we have a list
lst_1 = [i for i in range(10)]
lst_1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

### Numpy will do elementwise calculations

In [12]:
# arange() is similar to range()
np_arr1 = np.arange(10)
np_arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np_arr2 = np_arr1 + 2
np_arr2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### Creating Numpy arrays

In [ ]:
# np.array(list)

In [14]:
#Ex 1)
arr1 = np.array([1, 2, 3])
print(arr1)

[1 2 3]


In [15]:
#Ex 2)
arr2 = np.array([[1, 2, 3], [4, 5, 6], [6, 7, 8]])
print(arr2)

[[1 2 3]
 [4 5 6]
 [6 7 8]]


### np.arange(start,stop,step)

In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(1,15)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
np.arange(1,22,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [19]:
np.arange(21,0,-2)

array([21, 19, 17, 15, 13, 11,  9,  7,  5,  3,  1])

### Accessing and Slicing Numpy array elements

# 1D arrays

In [ ]:
# n-dimension array

In [20]:
# consider we have 2D array
a = np.array([[ 0,  1,  2,  3],[ 4,  5,  6,  7],[ 8,  9, 10, 11],[12, 13, 14, 15]])

In [21]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [22]:
# to access 10
# a[rowIndex,columnIndex]

a[2,2]

10

In [23]:
# to access 13
a[3,1]

13

In [24]:
# to get 0,1,4,5
a[0:2, 0:2]

array([[0, 1],
       [4, 5]])

In [25]:
# to get 10,11,14,15
a[2:,2:]

array([[10, 11],
       [14, 15]])

In [26]:
# similarly to get 5,6,9,10
a[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])