### Random numbers in numpy

In [ ]:
# np.random.random()
generates a random number from 0 to 1

In [1]:
import numpy as np

In [2]:
print(np.random.random())

0.8247243392073124


In [3]:
print(np.random.random())
print(np.random.random())
print(np.random.random())
print(np.random.random())

0.8286161550585313
0.467810851022313
0.898967104159557
0.31300258734560593


In [4]:
print(np.random.random())
print(np.random.random())
print(np.random.random())
print(np.random.random())

0.5850299815752336
0.6383173255330763
0.9802917839816164
0.03935027992439344


In [5]:
np.random.seed()

In [6]:
np.random.seed(100)
print(np.random.random())
print(np.random.random())
print(np.random.random())
print(np.random.random())

0.5434049417909654
0.27836938509379616
0.4245175907491331
0.8447761323199037


In [7]:
# you can specify the shape
x = np.random.random((4, 4))
x

array([[0.00471886, 0.12156912, 0.67074908, 0.82585276],
       [0.13670659, 0.57509333, 0.89132195, 0.20920212],
       [0.18532822, 0.10837689, 0.21969749, 0.97862378],
       [0.81168315, 0.17194101, 0.81622475, 0.27407375]])

### np.random.randint()

In [8]:
num = np.random.randint(low = 20, high =100)
num

79

In [9]:
num = np.random.randint(low = 20, high = 100, size = 5)
num

array([87, 27, 69, 67, 85])

### np.random.choice(list_of_choice,num_of_ele)

In [10]:
a = [24,27,22,47,35,82,-33,25,2.3,18]
a

[24, 27, 22, 47, 35, 82, -33, 25, 2.3, 18]

In [11]:
np.random.choice(a,size = 3)

array([25., 25., 24.])

In [12]:
np.random.choice(a,size = (5,5))

array([[ 22. ,  18. ,  18. ,  47. ,  22. ],
       [ 82. ,   2.3,  27. ,  24. ,  25. ],
       [-33. ,  22. ,  24. ,   2.3,  22. ],
       [ 82. ,  27. ,   2.3,  27. ,  82. ],
       [ 35. ,  22. ,   2.3,  47. ,  82. ]])

### Other Important functions

In [13]:
x = np.random.random((4, 4))
x

array([[0.76911517, 0.25069523, 0.28589569, 0.85239509],
       [0.97500649, 0.88485329, 0.35950784, 0.59885895],
       [0.35479561, 0.34019022, 0.17808099, 0.23769421],
       [0.04486228, 0.50543143, 0.37625245, 0.5928054 ]])

np.round()

In [15]:
# to round it to 3 decimal points
rounded = np.round(x, 3)
rounded

array([[0.769, 0.251, 0.286, 0.852],
       [0.975, 0.885, 0.36 , 0.599],
       [0.355, 0.34 , 0.178, 0.238],
       [0.045, 0.505, 0.376, 0.593]])

In [16]:
new = rounded * 100
new

array([[76.9, 25.1, 28.6, 85.2],
       [97.5, 88.5, 36. , 59.9],
       [35.5, 34. , 17.8, 23.8],
       [ 4.5, 50.5, 37.6, 59.3]])

astype()

In [17]:
# to change the data type of elements to integers
intt = new.astype(int)
intt

array([[76, 25, 28, 85],
       [97, 88, 36, 59],
       [35, 34, 17, 23],
       [ 4, 50, 37, 59]])